### PR TITLE
[fix](@svelteui/core): fix `dark-theme` class inconsistency

### LINKED ISSUE #334: Initial dark mode state - incorrect dark mode switching in AppShell example
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

I am basing this off of the example AppShell/Header/HeadContent starting here

https://github.com/svelteuidev/svelteui/blob/bfbd3c221b292fd9591abb1976f4e8c2ef64933d/packages/svelteui-demos/src/demos/core/AppShell/AppShell.demo.usage.svelte#L43

`isDark` determines whether or not dark mode is enabled or not. 

Set isDark to equal true at first instead of being false at first.

Now when dark mode is set initially with isDark 
  * Light mode is shown first for immediately flashing to dark mode (even with prepareStylesSSR)
  * Switching from dark mode which was set as default to light mode causes the Header - the svelteui generated nav class - to have a dark theme while the rest of the content correctly switches to light

image

image

Whenever dark mode is set initially this occurs. This is a one line change in the demo code, which a lot of users might do when exploring SvelteUI and will find that this doesn't work

### In which browser(s) did the problem occur?

_No response_

### Steps To Reproduce

Use svelteui demo code
Change `let isDark = false` to `let isDark = true`

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by longnguyen2004**
## Description

Making `currentTheme` reactive, so the wrapper `div` class syncs up with the `html` class. Partially fixes #334

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing guide](https://github.com/svelteuidev/svelteui/blob/main/CONTRIBUTING.md)
- [x] Prefix your PR title with `[@svelteui/core]`, `[@svelteui/actions]`, `[@svelteui/motion]`, `[@svelteui/core]`, `[core]`, or `[docs]`.
- [x] Include a description of the changes made in the PR description and in the commit messages.
- [ ] Include screenshots/videos of the changes made.
- [x] Verify that the linter and tests are passing, with `yarn lint` and `yarn test` or just run `yarn prepush`.

### CODE REVIEW

**Comment by BeeMargarida** [comment]
Hi! Thank you for this contribution! I'll not immediately merge since I want to analyze the issue again, since I'm not 100% sure what the cause yet.

**Comment by BeeMargarida** [comment]
Sorry, been busy with work, will check this out this week!

**Comment by BeeMargarida** [comment]
I can't seem to replicate the issue that this PR seems to fix. Can you?

**Comment by longnguyen2004** [comment]
Here's a StackBlitz repro of the issue https://stackblitz.com/edit/svelteui-dark-mode-bug-repro
And here's a video describing the bug

https://github.com/svelteuidev/svelteui/assets/15729831/4a68e257-de3f-4328-857f-0dc390663d5c

Basically, if the initial theme state is dark, then some components will be stuck in the dark state, because `currentTheme` is not reactive, so the `dark-theme` class is stuck on in the wrapper div.

There's also the issue of the background being initially white, before switching to dark, which is due to [this](https://github.com/svelteuidev/svelteui/blob/9f9f17aa5608cf138675a63f23f41a8455115481/packages/svelteui-core/src/styles/theme/SvelteUIProvider/SvelteUIProvider.svelte#L29-L33) not being SSR friendly. I didn't include a fix for that here, but I've outlined potential fixes for it in https://github.com/svelteuidev/svelteui/issues/334#issuecomment-1510995639

File: packages/svelteui-core/src/styles/theme/SvelteUIProvider/SvelteUIProvider.svelte [hunk 1]
```diff
@@ -36,7 +36,7 @@
 	const useStyles = createStyles(() => ({ root: {} }));
 	const forwardEvents = createEventForwarder(get_current_component());
 	const DEFAULT_THEME = useSvelteUITheme();
-	const currentTheme = () => {
+	$: currentTheme = () => {
```
Comment (BeeMargarida) [inline packages/svelteui-core/src/styles/theme/SvelteUIProvider/SvelteUIProvider.svelte:39]: Since we are changing this, lets change this variable to an object instead of a function, it makes no sense to be a function.

```suggestion
let currentTheme = null;
$: {
  if (themeObserver === null) currentTheme = null;
  currentTheme = themeObserver === 'light' ? (mergedTheme as unknown as string) : (dark as string);
};
```

(also change below when it's being used)

**Comment by BeeMargarida** [comment]
After merging this I'll make a new release, and fixing this for good will be the focus of the next one, I think

**Comment by longnguyen2004** [comment]
While you're at it, have a look at #373 and #370 too, those are trivial fixes

**Comment by BeeMargarida** [comment]
> While you're at it, have a look at #373 and #370 too, those are trivial fixes

Yap, looking at them now. I'll see if I can fix them and make a release this afternoon

File: packages/svelteui-core/src/styles/theme/SvelteUIProvider/SvelteUIProvider.svelte (hunk 1 above)
Comment (longnguyen2004) [reply packages/svelteui-core/src/styles/theme/SvelteUIProvider/SvelteUIProvider.svelte]: Done

**Review by BeeMargarida — APPROVED** [review]
